name: Remote Build Local Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Local APK Extension
        run: |
          mkdir -p build/
          echo "Building Krmzi Standalone Plugin..."
          # كود تجميع وهمي ذكي لإنشاء هيكلية APK يقرأها التطبيق محلياً
          zip -r build/KrmziProvider.apk src/
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KrmziExtension
          path: build/KrmziProvider.apk
